<form method="post" action="<?= $this->url->get('index/loginproses') ?>">

    <div class="form-group">
        <label>Username</label>
        <input class="form-control" type="text" name="username">
    </div>

    <div class="form-group">
        <label>Password</label>
        <input class="form-control" type="text" name="password">
    </div>


    <button class="btn btn-primary" type="submit">Login</button>
</form>